<?php


namespace App\Repositories;


use App\Inspiration;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class InspirationRepository extends BaseRepository
{

    public function __construct(Inspiration $model)
    {
        parent::__construct($model);
    }

    public function all()
    {
        return parent::all();
    }


    public function create(array $data)
    {


        $value = array('title' => $data[0]['title'], 'description' => $data[0]['description'], 'link' => $data[0]['link']);
        return parent::create($value);
        // TODO: Change the autogenerated stub
    }

    public function update(array $array, $id)
    {
        $value = array(
            [
                'title' => $array[0]['title'],
                'description' => $array[0]['description'],
                'link' => $array[0]['link']
            ]
        );
        $inspiration = Inspiration::findOrFail($id);
        $inspiration->title = $value[0]['title'];
        $inspiration->description = $value[0]['description'];
        $inspiration->link = $value[0]['link'];
        return $inspiration->save();
        // TODO: Implement updateInspiration() method.
    }

    public function show($id)
    {
        return parent::show($id); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
}
